class DrinkRecommendation {
  const DrinkRecommendation({
    required this.id,
    required this.brand,
    required this.name,
    required this.category,
    required this.description,
    required this.imagePath,
    required this.tags,
  });

  final String id;
  final String brand;
  final String name;
  final String category;
  final String description;
  final String imagePath;
  final List<String> tags;
}

class DrinkCatalog {
  DrinkCatalog._();

  static const String _root = 'assets/images/drinks';

  static const categories = [
    '健康区',
    '咖啡',
    '新茶饮',
    '即饮茶',
    '气泡',
    '果汁',
    '乳饮',
    '功能',
    '凉茶',
  ];

  static final List<DrinkRecommendation> drinks = [
    ..._curatedDrinks,
    ..._generatedDrinks,
  ];

  static const List<DrinkRecommendation> _curatedDrinks = [
    DrinkRecommendation(
      id: 'luckin',
      brand: '瑞幸咖啡',
      name: '冰拿铁 / 生椰拿铁',
      category: '咖啡',
      description: '清爽咖啡香配一点椰乳感，适合学习前给自己轻轻提神。',
      imagePath: '$_root/瑞幸咖啡.webp',
      tags: ['冰咖啡', '椰乳', '学习搭子'],
    ),
    DrinkRecommendation(
      id: 'cotti',
      brand: '库迪咖啡',
      name: '海盐芝士 / 海盐焦糖拿铁',
      category: '咖啡',
      description: '咸甜奶盖和咖啡底很有存在感，适合想喝点厚一点的时候。',
      imagePath: '$_root/库迪咖啡.webp',
      tags: ['拿铁', '海盐', '咸甜'],
    ),
    DrinkRecommendation(
      id: 'starbucks',
      brand: '星巴克',
      name: '抹茶星冰乐 / 绿茶星冰乐',
      category: '咖啡',
      description: '抹茶冰沙感很像给下午按了暂停键，适合奖励型休息。',
      imagePath: '$_root/星巴克.webp',
      tags: ['抹茶', '冰沙', '下午茶'],
    ),
    DrinkRecommendation(
      id: 'lucky_cup',
      brand: '幸运咖',
      name: '芒果椰乳拿铁 / 厚乳拿铁',
      category: '咖啡',
      description: '果香、椰香和厚乳都很友好，适合想喝甜但不想太复杂的时候。',
      imagePath: '$_root/幸运咖.webp',
      tags: ['厚乳', '芒果', '甜口'],
    ),
    DrinkRecommendation(
      id: 'nescafe',
      brand: '雀巢咖啡',
      name: '丝滑拿铁',
      category: '咖啡',
      description: '稳定、顺口、没负担，适合需要一杯熟悉咖啡味的日子。',
      imagePath: '$_root/雀巢咖啡.webp',
      tags: ['拿铁', '即饮', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'mixue',
      brand: '蜜雪冰城',
      name: '冰鲜柠檬水',
      category: '新茶饮',
      description: '酸甜清爽，适合走路、通勤和刚运动完的快乐一杯。',
      imagePath: '$_root/蜜雪冰城.webp',
      tags: ['柠檬', '清爽', '低负担'],
    ),
    DrinkRecommendation(
      id: 'guming',
      brand: '古茗',
      name: '超 A 芝士葡萄',
      category: '新茶饮',
      description: '葡萄果肉感很足，芝士奶盖让它更像一份小甜品。',
      imagePath: '$_root/古茗.webp',
      tags: ['葡萄', '芝士', '水果茶'],
    ),
    DrinkRecommendation(
      id: 'chabaidao',
      brand: '茶百道',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '芒果、西柚和奶香凑在一起，适合想要热带感的一天。',
      imagePath: '$_root/茶百道.webp',
      tags: ['芒果', '西柚', '甜品感'],
    ),
    DrinkRecommendation(
      id: 'chagee',
      brand: '霸王茶姬',
      name: '伯牙绝弦',
      category: '新茶饮',
      description: '茶香更突出的一杯，适合想喝奶茶但又想保留茶味的时候。',
      imagePath: '$_root/霸王茶姬.webp',
      tags: ['原叶茶', '奶茶', '茶香'],
    ),
    DrinkRecommendation(
      id: 'aunt_shanghai',
      brand: '沪上阿姨',
      name: '血糯米奶茶',
      category: '新茶饮',
      description: '糯叽叽的饱足感很强，适合把饮料当加餐的时刻。',
      imagePath: '$_root/沪上阿姨.webp',
      tags: ['血糯米', '奶茶', '加餐'],
    ),
    DrinkRecommendation(
      id: 'heytea',
      brand: '喜茶',
      name: '多肉葡萄',
      category: '新茶饮',
      description: '葡萄果味明亮，适合想喝一杯漂亮水果茶的时候。',
      imagePath: '$_root/喜茶.webp',
      tags: ['葡萄', '水果茶', '芝士'],
    ),
    DrinkRecommendation(
      id: 'nayuki',
      brand: '奈雪的茶',
      name: '霸气芝士草莓',
      category: '新茶饮',
      description: '草莓和芝士很有仪式感，适合心情需要被照顾一下。',
      imagePath: '$_root/奈雪的茶.webp',
      tags: ['草莓', '芝士', '仪式感'],
    ),
    DrinkRecommendation(
      id: 'yihetang',
      brand: '益禾堂',
      name: '益禾烤奶',
      category: '新茶饮',
      description: '烤奶香气温柔稳定，适合想喝经典奶茶的日子。',
      imagePath: '$_root/益禾堂.webp',
      tags: ['烤奶', '经典', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'shuyi',
      brand: '书亦烧仙草',
      name: '招牌烧仙草',
      category: '新茶饮',
      description: '料多、口感丰富，适合想慢慢喝完的一大杯。',
      imagePath: '$_root/书亦烧仙草.webp',
      tags: ['烧仙草', '料多', '饱足'],
    ),
    DrinkRecommendation(
      id: 'coco',
      brand: 'CoCo 都可',
      name: '百香双响炮',
      category: '新茶饮',
      description: '百香果酸甜加上双料口感，适合提起精神的小快乐。',
      imagePath: '$_root/CoCo 都可.webp',
      tags: ['百香果', '双料', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'chayan',
      brand: '茶颜悦色',
      name: '幽兰拿铁',
      category: '新茶饮',
      description: '茶、奶、奶油顶组合得很细腻，适合今天认真宠一下自己。',
      imagePath: '$_root/茶颜悦色.webp',
      tags: ['茶香', '奶油顶', '细腻'],
    ),
    DrinkRecommendation(
      id: 'linlee',
      brand: '柠季',
      name: '鸭屎香柠檬茶',
      category: '新茶饮',
      description: '柠檬和茶香都很醒神，适合犯困但不想喝咖啡的时候。',
      imagePath: '$_root/柠季.webp',
      tags: ['柠檬茶', '鸭屎香', '醒神'],
    ),
    DrinkRecommendation(
      id: 'sweet7',
      brand: '甜啦啦',
      name: '冰鲜柠檬水',
      category: '新茶饮',
      description: '简单清凉的一杯，适合天气热、嘴巴想要酸甜感的时候。',
      imagePath: '$_root/甜啦啦.webp',
      tags: ['柠檬', '冰饮', '清凉'],
    ),
    DrinkRecommendation(
      id: 'yidiandian',
      brand: '一点点',
      name: '波霸奶茶',
      category: '新茶饮',
      description: '珍珠奶茶的经典答案，适合想回到熟悉口味的一天。',
      imagePath: '$_root/一点点.webp',
      tags: ['波霸', '奶茶', '经典'],
    ),
    DrinkRecommendation(
      id: 'ksf_ice_tea',
      brand: '康师傅',
      name: '冰红茶',
      category: '即饮茶',
      description: '很有夏天记忆点的一瓶，适合想喝爽快茶味甜饮的时候。',
      imagePath: '$_root/冰红茶.webp',
      tags: ['红茶', '瓶装', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'ksf_green',
      brand: '康师傅',
      name: '绿茶',
      category: '即饮茶',
      description: '清甜绿茶味，适合吃饭或走路时顺手带一瓶。',
      imagePath: '$_root/绿茶.webp',
      tags: ['绿茶', '瓶装', '清甜'],
    ),
    DrinkRecommendation(
      id: 'ksf_jasmine',
      brand: '康师傅',
      name: '茉莉清茶',
      category: '即饮茶',
      description: '茉莉香气更轻柔，适合想喝茶味但不想太浓的时候。',
      imagePath: '$_root/茉莉清茶.webp',
      tags: ['茉莉', '清茶', '轻盈'],
    ),
    DrinkRecommendation(
      id: 'uni_ice_tea',
      brand: '统一',
      name: '统一冰红茶',
      category: '即饮茶',
      description: '酸甜茶感直接，适合想快速获得一口冰爽。',
      imagePath: '$_root/统一冰红茶.webp',
      tags: ['红茶', '瓶装', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'assam',
      brand: '统一',
      name: '阿萨姆奶茶',
      category: '即饮茶',
      description: '奶茶感浓郁稳定，适合想要方便又有满足感的一瓶。',
      imagePath: '$_root/阿萨姆奶茶.webp',
      tags: ['奶茶饮料', '阿萨姆', '浓郁'],
    ),
    DrinkRecommendation(
      id: 'plum_green',
      brand: '统一',
      name: '青梅绿茶',
      category: '即饮茶',
      description: '青梅酸甜混着绿茶，适合需要一点清爽转场的时候。',
      imagePath: '$_root/青梅绿茶.webp',
      tags: ['青梅', '绿茶', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'oriental_leaf',
      brand: '农夫山泉',
      name: '东方树叶',
      category: '即饮茶',
      description: '无糖茶的稳妥选择，适合想清口、控糖或配餐。',
      imagePath: '$_root/东方树叶.webp',
      tags: ['无糖茶', '配餐', '清口'],
    ),
    DrinkRecommendation(
      id: 'tea_pi',
      brand: '农夫山泉',
      name: '茶 π',
      category: '即饮茶',
      description: '果味茶更活泼，适合想在瓶装茶里喝到一点花样。',
      imagePath: '$_root/茶 π.webp',
      tags: ['果味茶', '瓶装', '轻甜'],
    ),
    DrinkRecommendation(
      id: 'suntory_oolong',
      brand: '三得利',
      name: '无糖乌龙茶',
      category: '即饮茶',
      description: '乌龙茶感干净利落，适合饭后和长时间工作时喝。',
      imagePath: '$_root/无糖乌龙茶.webp',
      tags: ['乌龙', '无糖', '饭后'],
    ),
    DrinkRecommendation(
      id: 'genki_ice_tea',
      brand: '元气森林',
      name: '冰茶系列',
      category: '即饮茶',
      description: '冰茶口味更轻快，适合想喝甜茶但别太厚重的时候。',
      imagePath: '$_root/冰茶系列.webp',
      tags: ['冰茶', '轻甜', '瓶装'],
    ),
    DrinkRecommendation(
      id: 'vita_lemon',
      brand: '维他',
      name: '维他柠檬茶',
      category: '即饮茶',
      description: '柠檬茶味很醒目，适合困顿下午来一点酸甜冲击。',
      imagePath: '$_root/维他柠檬茶.webp',
      tags: ['柠檬茶', '酸甜', '醒神'],
    ),
    DrinkRecommendation(
      id: 'coca',
      brand: '可口可乐',
      name: '可口可乐',
      category: '气泡',
      description: '快乐水就是快乐水，适合想给今天加一点气泡声。',
      imagePath: '$_root/可口可乐.webp',
      tags: ['碳酸', '经典', '快乐水'],
    ),
    DrinkRecommendation(
      id: 'pepsi',
      brand: '百事可乐',
      name: '百事可乐',
      category: '气泡',
      description: '直接、冰爽、很放松，适合搭配休息和小零食。',
      imagePath: '$_root/百事可乐.webp',
      tags: ['碳酸', '冰爽', '零食搭子'],
    ),
    DrinkRecommendation(
      id: 'genki_peach',
      brand: '元气森林',
      name: '白桃气泡水',
      category: '气泡',
      description: '白桃香和气泡感都很轻，适合想喝甜感但不想太腻。',
      imagePath: '$_root/白桃气泡水.webp',
      tags: ['白桃', '气泡水', '轻盈'],
    ),
    DrinkRecommendation(
      id: 'genki_sparkling',
      brand: '元气森林',
      name: '多种果味气泡水',
      category: '气泡',
      description: '果味气泡给选择困难一个简单答案，适合今天想要新鲜感。',
      imagePath: '$_root/多种果味气泡水.webp',
      tags: ['果味', '气泡水', '新鲜感'],
    ),
    DrinkRecommendation(
      id: 'c100',
      brand: '农夫山泉',
      name: '水溶 C100',
      category: '果汁',
      description: '酸酸甜甜的维 C 感，适合想喝清亮果味的时候。',
      imagePath: '$_root/水溶 C100.webp',
      tags: ['维C', '果味', '清爽'],
    ),
    DrinkRecommendation(
      id: 'nfc',
      brand: '农夫山泉',
      name: 'NFC 果汁',
      category: '果汁',
      description: '更像认真喝一杯果汁，适合早餐或加餐时刻。',
      imagePath: '$_root/NFC.webp',
      tags: ['NFC', '果汁', '早餐'],
    ),
    DrinkRecommendation(
      id: 'minute_maid',
      brand: '美汁源',
      name: '果粒橙',
      category: '果汁',
      description: '果粒口感很有记忆点，适合想喝橙味甜饮的时候。',
      imagePath: '$_root/美汁源.webp',
      tags: ['橙汁', '果粒', '经典'],
    ),
    DrinkRecommendation(
      id: 'suntory_lemon',
      brand: '三得利',
      name: '沁柠水',
      category: '果汁',
      description: '柠檬风味更轻，适合想要清爽但不想太甜的时候。',
      imagePath: '$_root/沁柠水.webp',
      tags: ['柠檬', '清淡', '轻甜'],
    ),
    DrinkRecommendation(
      id: 'hope_water',
      brand: '好望水',
      name: '望山楂 / 山楂草本饮',
      category: '果汁',
      description: '山楂和草本风味很东方，适合饭后或想换个口味。',
      imagePath: '$_root/好望水.webp',
      tags: ['山楂', '草本', '饭后'],
    ),
    DrinkRecommendation(
      id: 'ad_calcium',
      brand: '娃哈哈',
      name: 'AD 钙奶',
      category: '乳饮',
      description: '童年味道很明显，适合今天想喝一点轻松和可爱。',
      imagePath: '$_root/AD钙.webp',
      tags: ['乳饮', '童年', '甜口'],
    ),
    DrinkRecommendation(
      id: 'vita_soy',
      brand: '维他',
      name: '维他豆奶',
      category: '乳饮',
      description: '豆香温柔，适合早餐、夜晚或不想喝茶咖的时候。',
      imagePath: '$_root/维他豆奶.webp',
      tags: ['豆奶', '植物蛋白', '温柔'],
    ),
    DrinkRecommendation(
      id: 'yakult',
      brand: '养乐多',
      name: '养乐多乳酸菌饮品',
      category: '乳饮',
      description: '小小一瓶酸甜明亮，适合饭后给自己一个轻快收尾。',
      imagePath: '$_root/养乐多.webp',
      tags: ['乳酸菌', '酸甜', '饭后'],
    ),
    DrinkRecommendation(
      id: 'scream',
      brand: '尖叫',
      name: '尖叫运动饮料',
      category: '功能',
      description: '运动感很强，适合健身、出汗或长时间外出之后。',
      imagePath: '$_root/尖叫.webp',
      tags: ['运动', '补水', '出汗后'],
    ),
    DrinkRecommendation(
      id: 'eastroc',
      brand: '东鹏特饮',
      name: '东鹏特饮',
      category: '功能',
      description: '能量饮料存在感强，适合确实需要打起精神的场景。',
      imagePath: '$_root/东鹏特饮.webp',
      tags: ['能量', '提神', '慎喝'],
    ),
    DrinkRecommendation(
      id: 'mizone',
      brand: '脉动',
      name: '脉动维生素饮料',
      category: '功能',
      description: '运动后或户外时很顺手，适合补一点清爽果味。',
      imagePath: '$_root/脉动.webp',
      tags: ['维生素', '运动', '清爽'],
    ),
    DrinkRecommendation(
      id: 'wanglaoji',
      brand: '王老吉',
      name: '王老吉凉茶',
      category: '凉茶',
      description: '凉茶的经典答案，适合火锅、烧烤或重口味之后。',
      imagePath: '$_root/王老吉凉茶.webp',
      tags: ['凉茶', '草本', '配餐'],
    ),
  ];

  static final List<DrinkRecommendation> _generatedDrinks = [
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_76_36_9_44_1f',
      brand: 'CoCo 都可',
      name: '奶茶三兄弟',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__奶茶三兄弟.webp',
      tags: ['现制茶饮', 'CoCo 都可', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_76_1c_93_93_9c_36',
      brand: 'CoCo 都可',
      name: '奶霜莓莓果茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__奶霜莓莓果茶.webp',
      tags: ['现制茶饮', 'CoCo 都可', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_68_9d_18_32',
      brand: 'CoCo 都可',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__杨枝甘露.webp',
      tags: ['现制茶饮', 'CoCo 都可', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_e0_ac_30_9c_1a_1a',
      brand: 'CoCo 都可',
      name: '柠檬椰果多多',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__柠檬椰果多多.webp',
      tags: ['现制茶饮', 'CoCo 都可', '柠檬'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_cd_e0_76_36',
      brand: 'CoCo 都可',
      name: '珍珠奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__珍珠奶茶.webp',
      tags: ['现制茶饮', 'CoCo 都可', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_a2_9c_f_d0_d0',
      brand: 'CoCo 都可',
      name: '红果小姐姐',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__红果小姐姐.webp',
      tags: ['现制茶饮', 'CoCo 都可', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_c1_c2_f3_cd_e0_76_36',
      brand: 'CoCo 都可',
      name: '铁观音珍珠奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__铁观音珍珠奶茶.webp',
      tags: ['现制茶饮', 'CoCo 都可', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_52_85_e1_e1',
      brand: 'CoCo 都可',
      name: '青梅泡泡',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__青梅泡泡.webp',
      tags: ['现制茶饮', 'CoCo 都可', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_9c_8b_7f_73_32',
      brand: 'CoCo 都可',
      name: '鲜芋西米露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__鲜芋西米露.webp',
      tags: ['现制茶饮', 'CoCo 都可', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_43_6f_43_6f_20_fd_ef_5f_5f_9c_8b_52_1e_5b_76',
      brand: 'CoCo 都可',
      name: '鲜芋青稞牛奶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/CoCo 都可__鲜芋青稞牛奶.webp',
      tags: ['现制茶饮', 'CoCo 都可', '奶香'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_b0_c7_cb_a2_36',
      brand: '一点点',
      name: '冰淇淋红茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__冰淇淋红茶.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_ef_ef_ad_7e',
      brand: '一点点',
      name: '可可芭蕾',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__可可芭蕾.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_db_63_76_52',
      brand: '一点点',
      name: '四季奶青',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__四季奶青.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_db_63_25_36',
      brand: '一点点',
      name: '四季春茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__四季春茶.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_76_ff_c5_92',
      brand: '一点点',
      name: '奶绿装芒',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__奶绿装芒.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_b9_36_76_36',
      brand: '一点点',
      name: '抹茶奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__抹茶奶茶.webp',
      tags: ['现制茶饮', '一点点', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_e0_ac_7b_50_1a',
      brand: '一点点',
      name: '柠檬养乐多',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__柠檬养乐多.webp',
      tags: ['现制茶饮', '一点点', '柠檬'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_42_b1_76_4c',
      brand: '一点点',
      name: '桂花奶乌',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__桂花奶乌.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_a2_36_9b_47_35',
      brand: '一点点',
      name: '红茶玛奇朵',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__红茶玛奇朵.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_0_b9_b9_5f_5f_3f_4e_30',
      brand: '一点点',
      name: '阿华田',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/一点点__阿华田.webp',
      tags: ['现制茶饮', '一点点', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_68_9d_18_32',
      brand: '书亦烧仙草',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__杨枝甘露.webp',
      tags: ['现制茶饮', '书亦烧仙草', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_59_2b_71_36_b1',
      brand: '书亦烧仙草',
      name: '橙漫山茶花',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__橙漫山茶花.webp',
      tags: ['现制茶饮', '书亦烧仙草', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_5b_b9_9c_78_76_14',
      brand: '书亦烧仙草',
      name: '牛油果酸奶昔',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__牛油果酸奶昔.webp',
      tags: ['现制茶饮', '书亦烧仙草', '酸奶'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_1f_30_7f_dc',
      brand: '书亦烧仙草',
      name: '生椰西瓜',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__生椰西瓜.webp',
      tags: ['现制茶饮', '书亦烧仙草', '西瓜'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_7e_99_e4_a8',
      brand: '书亦烧仙草',
      name: '百香凤梨',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__百香凤梨.webp',
      tags: ['现制茶饮', '书亦烧仙草', '百香果'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_8b_e5_68_b6_8f',
      brand: '书亦烧仙草',
      name: '芋泥全家福',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__芋泥全家福.webp',
      tags: ['现制茶饮', '书亦烧仙草', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_9_89_7d_43_50',
      brand: '书亦烧仙草',
      name: '茉莉白桃子',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__茉莉白桃子.webp',
      tags: ['现制茶饮', '书亦烧仙草', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_49_93_76_91_bb_af',
      brand: '书亦烧仙草',
      name: '草莓奶云麻薯',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__草莓奶云麻薯.webp',
      tags: ['现制茶饮', '书亦烧仙草', '草莓'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_61_4_8b_6_bb_bb',
      brand: '书亦烧仙草',
      name: '葡萄芋圆冻冻',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__葡萄芋圆冻冻.webp',
      tags: ['现制茶饮', '书亦烧仙草', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_66_a6_e7_d9_49_5f_5f_d1_d6_f_8b_6_76_36',
      brand: '书亦烧仙草',
      name: '黑糖小芋圆奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/书亦烧仙草__黑糖小芋圆奶茶.webp',
      tags: ['现制茶饮', '书亦烧仙草', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_91_ad_9_89_7d',
      brand: '古茗',
      name: '云岭茉莉白',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__云岭茉莉白.webp',
      tags: ['现制茶饮', '古茗', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_27_d4_76_36',
      brand: '古茗',
      name: '大叔奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__大叔奶茶.webp',
      tags: ['现制茶饮', '古茗', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_3_7e_6_6_76_99',
      brand: '古茗',
      name: '布蕾脆脆奶芙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__布蕾脆脆奶芙.webp',
      tags: ['现制茶饮', '古茗', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_68_9d_18_32',
      brand: '古茗',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__杨枝甘露.webp',
      tags: ['现制茶饮', '古茗', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_e1_81_be',
      brand: '古茗',
      name: '泡鲁达',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__泡鲁达.webp',
      tags: ['现制茶饮', '古茗', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_1f_30_b9_36_bb_af',
      brand: '古茗',
      name: '生椰抹茶麻薯',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__生椰抹茶麻薯.webp',
      tags: ['现制茶饮', '古茗', '椰香'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_7e_99_cc_cd_4f',
      brand: '古茗',
      name: '百香双重奏',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__百香双重奏.webp',
      tags: ['现制茶饮', '古茗', '百香果'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_9d_eb_30_30',
      brand: '古茗',
      name: '芝士椰椰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__芝士椰椰.webp',
      tags: ['现制茶饮', '古茗', '椰香'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_7f_dc_30_30',
      brand: '古茗',
      name: '西瓜椰椰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__西瓜椰椰.webp',
      tags: ['现制茶饮', '古茗', '西瓜'],
    ),
    DrinkRecommendation(
      id: 'drink_e4_17_5f_5f_99_95_99_52_e2_76_36',
      brand: '古茗',
      name: '龙井香青团奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/古茗__龙井香青团奶茶.webp',
      tags: ['现制茶饮', '古茗', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_9c_36_ff_8d',
      brand: '喜茶',
      name: '喜茶绿妍',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__喜茶绿妍.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_1a_89_43_4e',
      brand: '喜茶',
      name: '多肉桃李',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__多肉桃李.webp',
      tags: ['现制茶饮', '喜茶', '蜜桃'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_1a_89_92_92_18_32',
      brand: '喜茶',
      name: '多肉芒芒甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__多肉芒芒甘露.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_d0_c9_73_cf_f1_a2',
      brand: '喜茶',
      name: '提拉米苏英红',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__提拉米苏英红.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_e1_6f_a2_da',
      brand: '喜茶',
      name: '满杯红柚',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__满杯红柚.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_e4_d1_d6_e2_e2_5b_73',
      brand: '喜茶',
      name: '烤黑糖波波牛乳',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__烤黑糖波波牛乳.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_6_41_27_58',
      brand: '喜茶',
      name: '爆汁大橘',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__爆汁大橘.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_8b_e5_e2_e2_5b_73',
      brand: '喜茶',
      name: '芋泥波波牛乳',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__芋泥波波牛乳.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_9d_9d_93_93',
      brand: '喜茶',
      name: '芝芝莓莓',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__芝芝莓莓.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_9c_36_5f_5f_7b_e2_e2_5b_73',
      brand: '喜茶',
      name: '轻波波牛乳',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/喜茶__轻波波牛乳.webp',
      tags: ['现制茶饮', '喜茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_9a_9a_8b_e5_9d_cf_36',
      brand: '奈雪的茶',
      name: '厚厚芋泥宝藏茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__厚厚芋泥宝藏茶.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_48_ea_1d_32',
      brand: '奈雪的茶',
      name: '奈雪初露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__奈雪初露.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_68_9d_18_32',
      brand: '奈雪的茶',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__杨枝甘露.webp',
      tags: ['现制茶饮', '奈雪的茶', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_d1_72_71_9_cd_e0_76_36',
      brand: '奈雪的茶',
      name: '金色山脉珍珠奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__金色山脉珍珠奶茶.webp',
      tags: ['现制茶饮', '奈雪的茶', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_38_14_59_50',
      brand: '奈雪的茶',
      name: '霸气橙子',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__霸气橙子.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_38_14_6_92_ad_50',
      brand: '奈雪的茶',
      name: '霸气脆芒芭乐',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__霸气脆芒芭乐.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_38_14_9d_eb_92_9c',
      brand: '奈雪的茶',
      name: '霸气芝士芒果',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__霸气芝士芒果.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_38_14_9d_eb_61_4',
      brand: '奈雪的茶',
      name: '霸气芝士葡萄',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__霸气芝士葡萄.webp',
      tags: ['现制茶饮', '奈雪的茶', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_2d_4e_99_9d_cf_36',
      brand: '奈雪的茶',
      name: '鸭屎香宝藏茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__鸭屎香宝藏茶.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_48_ea_84_36_5f_5f_d1_d6_e0_e0_9d_cf_36',
      brand: '奈雪的茶',
      name: '黑糖珠珠宝藏茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/奈雪的茶__黑糖珠珠宝藏茶.webp',
      tags: ['现制茶饮', '奈雪的茶', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_1a_93_b0_36',
      brand: '幸运咖',
      name: '多莓冰茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__多莓冰茶.webp',
      tags: ['咖啡系', '幸运咖', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_ad_57_54_9d_ff_c1',
      brand: '幸运咖',
      name: '岭南荔枝拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__岭南荔枝拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_db_4c_b0_ff_c1',
      brand: '幸运咖',
      name: '招牌冰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__招牌冰拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_db_4c_9a_73_ff_c1',
      brand: '幸运咖',
      name: '招牌厚乳拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__招牌厚乳拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_42_b1_ff_c1',
      brand: '幸运咖',
      name: '桂花拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__桂花拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_30_30_ff_c1',
      brand: '幸运咖',
      name: '椰椰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__椰椰拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_1f_59_ff_c1',
      brand: '幸运咖',
      name: '真橙拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__真橙拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_a2_f3_b4_b0_3_96',
      brand: '幸运咖',
      name: '红石榴冰萃咖',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__红石榴冰萃咖.webp',
      tags: ['咖啡系', '幸运咖', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_cf_78_ff_c1',
      brand: '幸运咖',
      name: '经典拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__经典拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_cf_78_8e_f_8_35_2e_39_20_43_77_9',
      brand: '幸运咖',
      name: '经典美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__经典美式（5.9 元起）.webp',
      tags: ['咖啡系', '幸运咖', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_9d_9d_6a_6a_ff_c1',
      brand: '幸运咖',
      name: '芝芝酪酪拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__芝芝酪酪拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_ad_50_ff_c1',
      brand: '幸运咖',
      name: '芭乐拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__芭乐拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_49_93_b0_ff_c1',
      brand: '幸运咖',
      name: '草莓冰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__草莓冰拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_49_93_bb_bb_23_e3',
      brand: '幸运咖',
      name: '草莓冻冻圣代',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__草莓冻冻圣代.webp',
      tags: ['咖啡系', '幸运咖', '草莓'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_dd_b_cb_30_30_ff_c1',
      brand: '幸运咖',
      name: '蓝朋友椰椰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__蓝朋友椰椰拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_52_d0_b0_3_96',
      brand: '幸运咖',
      name: '青提冰萃咖',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__青提冰萃咖.webp',
      tags: ['咖啡系', '幸运咖', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_ce_c9_ff_46_99_ff_c1',
      brand: '幸运咖',
      name: '风凉绿豆沙拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__风凉绿豆沙拿铁.webp',
      tags: ['咖啡系', '幸运咖', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_99_34_e0_ac_96',
      brand: '幸运咖',
      name: '香水柠檬咖',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__香水柠檬咖.webp',
      tags: ['咖啡系', '幸运咖', '柠檬'],
    ),
    DrinkRecommendation(
      id: 'drink_78_d0_96_5f_5f_99_49_bb_e0_36',
      brand: '幸运咖',
      name: '香草冻柠茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/幸运咖__香草冻柠茶.webp',
      tags: ['咖啡系', '幸运咖', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_cc_30_ff_c1',
      brand: '库迪咖啡',
      name: '双椰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__双椰拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_b8_d5_6a_99_49_ff_c1',
      brand: '库迪咖啡',
      name: '咸法酪香草拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__咸法酪香草拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f_c4_b9_ff_c1',
      brand: '库迪咖啡',
      name: '小黄油拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__小黄油拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f_c4_b9_ff_c1_32',
      brand: '库迪咖啡',
      name: '小黄油拿铁2',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__小黄油拿铁2.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f_c4_b9_8e_f',
      brand: '库迪咖啡',
      name: '小黄油美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__小黄油美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f_c4_b9_9_99_b9_36',
      brand: '库迪咖啡',
      name: '小黄油茉香抹茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__小黄油茉香抹茶.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_4f_ae_34',
      brand: '库迪咖啡',
      name: '杏皮水',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__杏皮水.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_68_9d_18_32',
      brand: '库迪咖啡',
      name: '杨枝甘露',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__杨枝甘露.webp',
      tags: ['咖啡系', '库迪咖啡', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_68_9d_18_32_ff_c1',
      brand: '库迪咖啡',
      name: '杨枝甘露拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__杨枝甘露拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_da_c1_8e_f',
      brand: '库迪咖啡',
      name: '柚见美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__柚见美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_59_20_43_20_8e_f',
      brand: '库迪咖啡',
      name: '橙 C 美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__橙 C 美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_41_91_9_89_7b_73_36',
      brand: '库迪咖啡',
      name: '流云茉莉轻乳茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__流云茉莉轻乳茶.webp',
      tags: ['咖啡系', '库迪咖啡', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_5_3d_ad_50_d0',
      brand: '库迪咖啡',
      name: '清爽芭乐提',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__清爽芭乐提.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_5_3d_ad_50_d0_20_4f_ae_34',
      brand: '库迪咖啡',
      name: '清爽芭乐提 杏皮水',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__清爽芭乐提 杏皮水.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_1f_30_ff_c1',
      brand: '库迪咖啡',
      name: '生椰拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__生椰拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_7e_99_59_59_8e_f',
      brand: '库迪咖啡',
      name: '百香橙橙美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__百香橙橙美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_a2_46_1f_6a_5b_73_36',
      brand: '库迪咖啡',
      name: '红豆生酪牛乳茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__红豆生酪牛乳茶.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_cf_78_ff_c1',
      brand: '库迪咖啡',
      name: '经典拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__经典拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f6_9f_93_9c_b0_36',
      brand: '库迪咖啡',
      name: '胶原莓果冰茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__胶原莓果冰茶.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f6_9f_93_9c_76_14',
      brand: '库迪咖啡',
      name: '胶原莓果奶昔',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__胶原莓果奶昔.webp',
      tags: ['咖啡系', '库迪咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_f6_9f_93_9c_8e_f',
      brand: '库迪咖啡',
      name: '胶原莓果美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__胶原莓果美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_9_89_b1_99_ff_c1',
      brand: '库迪咖啡',
      name: '茉莉花香拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__茉莉花香拿铁.webp',
      tags: ['咖啡系', '库迪咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_7f_7f_cc_8e_f',
      brand: '库迪咖啡',
      name: '西西里美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__西西里美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_d1_56_f1_d8_8e_f',
      brand: '库迪咖啡',
      name: '金奖深烘美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__金奖深烘美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_93_ea_5f_5f_33_49_52_d0_8e_f',
      brand: '库迪咖啡',
      name: '阳光青提美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/库迪__阳光青提美式.webp',
      tags: ['咖啡系', '库迪咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_4f_41_54_4c_59_1a_d5_a6_76',
      brand: 'OATLY',
      name: '燕麦奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__OATLY：燕麦奶.webp',
      tags: ['乳饮系', 'OATLY', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_3_9c',
      brand: '七喜',
      name: '七喜',
      category: '气泡',
      description: '气泡感会让心情更轻一点，适合想要一口冰爽的时候。',
      imagePath: '$_root/新饮品__七喜.webp',
      tags: ['气泡饮', '七喜', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_9_43_81_f4_9c_5b_76',
      brand: '三元',
      name: '极致鲜牛奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__三元极致鲜牛奶.webp',
      tags: ['乳饮系', '三元', '奶香'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_9_97_29_1a_29_a3_ff_c1',
      brand: '三得利',
      name: '利趣拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/新饮品__三得利：利趣拿铁.webp',
      tags: ['咖啡系', '三得利', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_50_4e',
      brand: '乐虎',
      name: '乐虎',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__乐虎.webp',
      tags: ['功能饮', '乐虎', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_a_29_89_55_c',
      brand: '伊利',
      name: '安慕希',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__伊利安慕希.webp',
      tags: ['乳饮系', '伊利', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_a_29_1a_18_78_73',
      brand: '伊利',
      name: '优酸乳',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__伊利：优酸乳.webp',
      tags: ['乳饮系', '伊利', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_73_97_50',
      brand: '佳得乐',
      name: '佳得乐',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__佳得乐.webp',
      tags: ['功能饮', '佳得乐', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_65_9b_9d_1a_59_1c_73_d0_a8_7d_34',
      brand: '健力宝',
      name: '橙蜜味运动汽水',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__健力宝：橙蜜味运动汽水.webp',
      tags: ['功能饮', '健力宝', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_43_14_ee_97_1a_73_36_fb_17',
      brand: '元气森林',
      name: '乳茶系列',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__元气森林：乳茶系列.webp',
      tags: ['乳饮系', '元气森林', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_49_e_18_d_9c_5b_76',
      brand: '光明优倍',
      name: '鲜牛奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__光明优倍鲜牛奶.webp',
      tags: ['乳饮系', '光明优倍', '奶香'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_49_e_f4_18_1f_d7_9c_76',
      brand: '光明致优娟姗',
      name: '鲜奶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/新饮品__光明致优娟姗鲜奶.webp',
      tags: ['现制茶饮', '光明致优娟姗', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_49_e_ab_af_29_89',
      brand: '光明莫斯利安',
      name: '光明莫斯利安',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__光明莫斯利安.webp',
      tags: ['乳饮系', '光明莫斯利安', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_6d_2a_38_43_1a_38_43_73',
      brand: '六个核桃',
      name: '核桃乳',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__六个核桃：核桃乳.webp',
      tags: ['乳饮系', '六个核桃', '蜜桃'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_70_b3_ed_33_2f_76_36',
      brand: '兰芳园',
      name: '鸳鸯奶茶',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__兰芳园鸳鸯奶茶.webp',
      tags: ['瓶装茶', '兰芳园', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_70_b3_ed_1a_1d_9c_76_36',
      brand: '兰芳园',
      name: '丝袜奶茶',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__兰芳园：丝袜奶茶.webp',
      tags: ['瓶装茶', '兰芳园', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_9c_2b_71_c9_ad_cc_e0_d6_96_61',
      brand: '农夫山泉炭仌',
      name: '无糖咖啡',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/新饮品__农夫山泉炭仌无糖咖啡.webp',
      tags: ['咖啡系', '农夫山泉炭仌', '轻负担'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_ef_e3_ef_50_d7_b_1a_ea_a7',
      brand: '可口可乐旗下',
      name: '雪碧',
      category: '气泡',
      description: '气泡感会让心情更轻一点，适合想要一口冰爽的时候。',
      imagePath: '$_root/新饮品__可口可乐旗下：雪碧.webp',
      tags: ['气泡饮', '可口可乐旗下', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_1b_50_9d_a6_9c_3b',
      brand: '君乐宝悦鲜活',
      name: '君乐宝悦鲜活',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__君乐宝悦鲜活.webp',
      tags: ['乳饮系', '君乐宝悦鲜活', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_1b_50_9d_80_87',
      brand: '君乐宝简醇',
      name: '君乐宝简醇',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__君乐宝简醇.webp',
      tags: ['乳饮系', '君乐宝简醇', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_73_68_1a_cf_e5_20_43_20_9c_9c_41',
      brand: '味全',
      name: '每日 C 鲜果汁',
      category: '果汁',
      description: '果味更明亮，适合早餐、加餐或想喝点清甜风味的时候。',
      imagePath: '$_root/新饮品__味全：每日 C 鲜果汁.webp',
      tags: ['果汁系', '味全', '果味'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_16_1f_ba',
      brand: '外星人',
      name: '外星人',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__外星人.webp',
      tags: ['功能饮', '外星人', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_3_c8_c8_1a_25_7b_eb_bf',
      brand: '娃哈哈',
      name: '营养快线',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__娃哈哈：营养快线.webp',
      tags: ['乳饮系', '娃哈哈', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_9d_ff_9b_34_79',
      brand: '宝矿力水特',
      name: '宝矿力水特',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__宝矿力水特.webp',
      tags: ['功能饮', '宝矿力水特', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_b7_8_85_1a_cf_78_76_36',
      brand: '康师傅',
      name: '经典奶茶',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__康师傅：经典奶茶.webp',
      tags: ['瓶装茶', '康师傅', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_21_c9_1a_cf_53_34',
      brand: '怡泉',
      name: '苏打水',
      category: '健康区',
      description: '轻负担和补水感更明确，适合今天想喝得清爽一点。',
      imagePath: '$_root/新饮品__怡泉：苏打水.webp',
      tags: ['轻负担', '怡泉', '气泡感'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_e0_d6_ef_50',
      brand: '轻负担',
      name: '无糖可乐',
      category: '健康区',
      description: '轻负担和补水感更明确，适合今天想喝得清爽一点。',
      imagePath: '$_root/新饮品__无糖可乐.webp',
      tags: ['轻负担', '清爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_fa_d4_1a_fa_d4_5b_76',
      brand: '旺仔',
      name: '旺仔牛奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__旺仔：旺仔牛奶.webp',
      tags: ['乳饮系', '旺仔', '奶香'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_1f_f4_4b_1f_9',
      brand: '星巴克星选',
      name: '星巴克星选',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/新饮品__星巴克星选.webp',
      tags: ['咖啡系', '星巴克星选', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_30_11_1a_30_41',
      brand: '椰树',
      name: '椰汁',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__椰树：椰汁.webp',
      tags: ['乳饮系', '椰树', '椰香'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_47_90_1a_31_30_30_25_20_af_9c_41_fb_17',
      brand: '汇源',
      name: '100% 纯果汁系列',
      category: '果汁',
      description: '果味更明亮，适合早餐、加餐或想喝点清甜风味的时候。',
      imagePath: '$_root/新饮品__汇源：100% 纯果汁系列.webp',
      tags: ['果汁系', '汇源', '果味'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_4e_36_76_ff_8_e5_f_4e_36_ce_73',
      brand: '煎茶奶绿（日式煎茶风味',
      name: '煎茶奶绿（日式煎茶风味',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__煎茶奶绿（日式煎茶风味.webp',
      tags: ['瓶装茶', '煎茶奶绿（日式煎茶风味', '通勤搭子'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_7d_0_34_1a_9d',
      brand: '轻补水',
      name: '白开水多喝',
      category: '健康区',
      description: '轻负担和补水感更明确，适合今天想喝得清爽一点。',
      imagePath: '$_root/新饮品__白开水多喝.webp',
      tags: ['轻负担', '补水', '清爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_ff_c9_34',
      brand: '轻补水',
      name: '矿泉水',
      category: '健康区',
      description: '轻负担和补水感更明确，适合今天想喝得清爽一点。',
      imagePath: '$_root/新饮品__矿泉水.webp',
      tags: ['轻负担', '补水', '清爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_a2_5b',
      brand: '红牛',
      name: '红牛',
      category: '功能',
      description: '补给感和提神感更强，适合运动后、出门久了或需要打起精神的时候。',
      imagePath: '$_root/新饮品__红牛.webp',
      tags: ['功能饮', '红牛', '补给'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_df_0_3f_28_c6_1a_9_89_76_ff',
      brand: '统一阿萨姆',
      name: '茉莉奶绿',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__统一阿萨姆：茉莉奶绿.webp',
      tags: ['瓶装茶', '统一阿萨姆', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_8e_74_be',
      brand: '美年达',
      name: '美年达',
      category: '气泡',
      description: '气泡感会让心情更轻一点，适合想要一口冰爽的时候。',
      imagePath: '$_root/新饮品__美年达.webp',
      tags: ['气泡饮', '美年达', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_ac_be',
      brand: '芬达',
      name: '芬达',
      category: '气泡',
      description: '气泡感会让心情更轻一点，适合想要一口冰爽的时候。',
      imagePath: '$_root/新饮品__芬达.webp',
      tags: ['气泡饮', '芬达', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_99_5b_cf_e5_9c_ed',
      brand: '蒙牛',
      name: '每日鲜语',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__蒙牛每日鲜语.webp',
      tags: ['乳饮系', '蒙牛', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_99_5b_af_4',
      brand: '蒙牛',
      name: '纯甄',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__蒙牛纯甄.webp',
      tags: ['乳饮系', '蒙牛', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_a4_7b_0_34_5b_38_29_78_76',
      brand: '认养一头牛',
      name: '常温酸奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__认养一头牛常温酸奶.webp',
      tags: ['乳饮系', '认养一头牛', '酸奶'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_f6_6d_1a_b1_1f_5b_76',
      brand: '银鹭',
      name: '花生牛奶',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__银鹭：花生牛奶.webp',
      tags: ['乳饮系', '银鹭', '奶香'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_3f_28_c6_7d_43_c2_f3_8_7d_43_20_2b_20_c1_c2_f3_9c_73_76_36_9',
      brand: '阿萨姆白桃观音（白桃 + 铁观音果味奶茶）',
      name: '阿萨姆白桃观音（白桃 + 铁观音果味奶茶）',
      category: '即饮茶',
      description: '方便顺手、味道稳定，适合通勤、配餐或路上来一瓶。',
      imagePath: '$_root/新饮品__阿萨姆白桃观音（白桃 + 铁观音果味奶茶）.webp',
      tags: ['瓶装茶', '阿萨姆白桃观音（白桃 + 铁观音果味奶茶）', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_c0_e2_1d_d1_ff_c1',
      brand: '雀巢',
      name: '丝滑拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/新饮品__雀巢丝滑拿铁.webp',
      tags: ['咖啡系', '雀巢', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_32_32_1a_4f_c1_32',
      brand: '露露',
      name: '杏仁露',
      category: '乳饮',
      description: '奶香和顺滑感会更明显，适合当作轻早餐或安抚型小奖励。',
      imagePath: '$_root/新饮品__露露：杏仁露.webp',
      tags: ['乳饮系', '露露', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'drink_b0_6e_c1_5f_5f_99_d8_d8_1a_4d_65_63_6f',
      brand: '香飘飘',
      name: 'Meco',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/新饮品__香飘飘：Meco.webp',
      tags: ['现制茶饮', '香飘飘', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_4a_61_76_61_20_8e_47_1f_b0_50',
      brand: '星巴克',
      name: 'Java 碎片星冰乐',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__Java 碎片星冰乐.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_2f_35_a2_36',
      brand: '星巴克',
      name: '伯爵红茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__伯爵红茶.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_61_3_47_fa',
      brand: '星巴克',
      name: '卡布奇诺',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__卡布奇诺.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_27_aa_30_99_49_f4_e6_28_ff_c1',
      brand: '星巴克',
      name: '大溪地香草巴旦木拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__大溪地香草巴旦木拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_f4_e6_28_ff_c1',
      brand: '星巴克',
      name: '巴旦木拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__巴旦木拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_b9_36_ff_c1',
      brand: '星巴克',
      name: '抹茶拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__抹茶拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_ff_c1',
      brand: '星巴克',
      name: '拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_69_61_1f_b0_50',
      brand: '星巴克',
      name: '摩卡星冰乐',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__摩卡星冰乐.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_9b_9c_ce_73_ff_c1',
      brand: '星巴克',
      name: '榛果风味拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__榛果风味拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_53_c1_96_61_ff_c1',
      brand: '星巴克',
      name: '浓郁咖啡拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__浓郁咖啡拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_26_d6_9b_47_35',
      brand: '星巴克',
      name: '焦糖玛奇朵',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__焦糖玛奇朵.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_d5_a6_1d_d2_ff_c1',
      brand: '星巴克',
      name: '燕麦丝绒拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__燕麦丝绒拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_d5_a6_ff_c1',
      brand: '星巴克',
      name: '燕麦拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__燕麦拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_d5_a6_26_d6_9b_47_35',
      brand: '星巴克',
      name: '燕麦焦糖玛奇朵',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__燕麦焦糖玛奇朵.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_a2_36_ff_c1',
      brand: '星巴克',
      name: '红茶拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__红茶拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_8e_f_96_61',
      brand: '星巴克',
      name: '美式咖啡',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__美式咖啡.webp',
      tags: ['咖啡系', '星巴克', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_f1_f_e9_10_a2_36',
      brand: '星巴克',
      name: '英式早餐红茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__英式早餐红茶.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_49_93_76_b9_1f_b0_50',
      brand: '星巴克',
      name: '草莓奶油星冰乐',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__草莓奶油星冰乐.webp',
      tags: ['咖啡系', '星巴克', '草莓'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_99_49_ff_c1',
      brand: '星巴克',
      name: '香草拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__香草拿铁.webp',
      tags: ['咖啡系', '星巴克', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1f_f4_4b_5f_5f_a5_ae_7d',
      brand: '星巴克',
      name: '馥芮白',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/星巴克__馥芮白.webp',
      tags: ['咖啡系', '星巴克', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_51_51_20_8b_e5_73_bb_af',
      brand: '沪上阿姨',
      name: 'QQ 芋泥米麻薯',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__QQ 芋泥米麻薯.webp',
      tags: ['现制茶饮', '沪上阿姨', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_d9_d9_ab_70_52_d0',
      brand: '沪上阿姨',
      name: '仙仙玫瑰青提',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__仙仙玫瑰青提.webp',
      tags: ['现制茶饮', '沪上阿姨', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_9a_8b_e5_e2_e2_76_36',
      brand: '沪上阿姨',
      name: '厚芋泥波波奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__厚芋泥波波奶茶.webp',
      tags: ['现制茶饮', '沪上阿姨', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_d_e4_cb_d5_76_36',
      brand: '沪上阿姨',
      name: '复古蛋糕奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__复古蛋糕奶茶.webp',
      tags: ['现制茶饮', '沪上阿姨', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_1a_89_61_4_d1_16',
      brand: '沪上阿姨',
      name: '多肉葡萄金砖',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__多肉葡萄金砖.webp',
      tags: ['现制茶饮', '沪上阿姨', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_68_9d_18_32',
      brand: '沪上阿姨',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__杨枝甘露.webp',
      tags: ['现制茶饮', '沪上阿姨', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_ff_46_5b_73_b0',
      brand: '沪上阿姨',
      name: '绿豆牛乳冰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__绿豆牛乳冰.webp',
      tags: ['现制茶饮', '沪上阿姨', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_9_89_76_ff',
      brand: '沪上阿姨',
      name: '茉莉奶绿',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__茉莉奶绿.webp',
      tags: ['现制茶饮', '沪上阿姨', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_7f_dc_30_30',
      brand: '沪上阿姨',
      name: '西瓜椰椰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__西瓜椰椰.webp',
      tags: ['现制茶饮', '沪上阿姨', '西瓜'],
    ),
    DrinkRecommendation(
      id: 'drink_aa_a_3f_e8_5f_5f_85_f2_49_93_27_8f',
      brand: '沪上阿姨',
      name: '超嗲草莓大福',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/沪上阿姨__超嗲草莓大福.webp',
      tags: ['现制茶饮', '沪上阿姨', '草莓'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_a0_53_b7_3',
      brand: '瑞幸咖啡',
      name: '加浓冷萃',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__加浓冷萃.webp',
      tags: ['咖啡系', '瑞幸咖啡', '冷萃'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_a0_53_8e_f',
      brand: '瑞幸咖啡',
      name: '加浓美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__加浓美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_61_3_47_fa',
      brand: '瑞幸咖啡',
      name: '卡布奇诺',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__卡布奇诺.webp',
      tags: ['咖啡系', '瑞幸咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_9a_73_ff_c1',
      brand: '瑞幸咖啡',
      name: '厚乳拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__厚乳拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_f_c4_4f_8e_f',
      brand: '瑞幸咖啡',
      name: '小黄杏美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__小黄杏美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_f_c4_b9_ff_c1',
      brand: '瑞幸咖啡',
      name: '小黄油拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__小黄油拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_69_61',
      brand: '瑞幸咖啡',
      name: '摩卡',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__摩卡.webp',
      tags: ['咖啡系', '瑞幸咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_d1_58_b7_3',
      brand: '瑞幸咖啡',
      name: '柑橘冷萃',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__柑橘冷萃.webp',
      tags: ['咖啡系', '瑞幸咖啡', '冷萃'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_da_20_43_20_8e_f',
      brand: '瑞幸咖啡',
      name: '柚 C 美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__柚 C 美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_7_c6_b7_3',
      brand: '瑞幸咖啡',
      name: '标准冷萃',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__标准冷萃.webp',
      tags: ['咖啡系', '瑞幸咖啡', '冷萃'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_7_c6_8e_f',
      brand: '瑞幸咖啡',
      name: '标准美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__标准美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_30_99_b7_3',
      brand: '瑞幸咖啡',
      name: '椰香冷萃',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__椰香冷萃.webp',
      tags: ['咖啡系', '瑞幸咖啡', '冷萃'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_9b_9c_ff_c1',
      brand: '瑞幸咖啡',
      name: '榛果拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__榛果拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_59_20_43_20_8e_f',
      brand: '瑞幸咖啡',
      name: '橙 C 美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__橙 C 美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_1f_6a_ff_c1',
      brand: '瑞幸咖啡',
      name: '生酪拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__生酪拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_af_c2_a2_36_ff_c1',
      brand: '瑞幸咖啡',
      name: '疯狂红茶拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__疯狂红茶拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_be_b9_b3_5e_7d',
      brand: '瑞幸咖啡',
      name: '精粹澳瑞白',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__精粹澳瑞白.webp',
      tags: ['咖啡系', '瑞幸咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_cf_78_ff_c1',
      brand: '瑞幸咖啡',
      name: '经典拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__经典拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_36_a0_ea_f2_8e_f',
      brand: '瑞幸咖啡',
      name: '耶加雪菲美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__耶加雪菲美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_9_89_b1_99_ff_c1',
      brand: '瑞幸咖啡',
      name: '茉莉花香拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__茉莉花香拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_61_4_b0_3_8e_f',
      brand: '瑞幸咖啡',
      name: '葡萄冰萃美式',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__葡萄冰萃美式.webp',
      tags: ['咖啡系', '瑞幸咖啡', '美式'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_ea_50_a2_36',
      brand: '瑞幸咖啡',
      name: '雪乐红茶',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__雪乐红茶.webp',
      tags: ['咖啡系', '瑞幸咖啡', '提神'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_52_d0_9_89_b7_3',
      brand: '瑞幸咖啡',
      name: '青提茉莉冷萃',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__青提茉莉冷萃.webp',
      tags: ['咖啡系', '瑞幸咖啡', '冷萃'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_99_49_1d_d2_ff_c1',
      brand: '瑞幸咖啡',
      name: '香草丝绒拿铁',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__香草丝绒拿铁.webp',
      tags: ['咖啡系', '瑞幸咖啡', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_5e_78_5f_5f_9c_3_7b_7b_9_89',
      brand: '瑞幸咖啡',
      name: '鲜萃轻轻茉莉',
      category: '咖啡',
      description: '咖啡香更直接，适合学习、工作或想让状态清醒一点的时候。',
      imagePath: '$_root/瑞幸__鲜萃轻轻茉莉.webp',
      tags: ['咖啡系', '瑞幸咖啡', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_0_76_68_b6_8f',
      brand: '甜啦啦',
      name: '一桶全家福',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__一桶全家福.webp',
      tags: ['现制茶饮', '甜啦啦', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_0_76_34_9c_36',
      brand: '甜啦啦',
      name: '一桶水果茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__一桶水果茶.webp',
      tags: ['现制茶饮', '甜啦啦', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_db_63_9c_ed',
      brand: '甜啦啦',
      name: '四季果园',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__四季果园.webp',
      tags: ['现制茶饮', '甜啦啦', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_e0_4c_68_57_76_36',
      brand: '甜啦啦',
      name: '无敌全套奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__无敌全套奶茶.webp',
      tags: ['现制茶饮', '甜啦啦', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_68_9d_18_32',
      brand: '甜啦啦',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__杨枝甘露.webp',
      tags: ['现制茶饮', '甜啦啦', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_1f_30_ff_c1',
      brand: '甜啦啦',
      name: '生椰拿铁',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__生椰拿铁.webp',
      tags: ['现制茶饮', '甜啦啦', '拿铁'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_7e_99_d1_e0_1d',
      brand: '甜啦啦',
      name: '百香金菠萝',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__百香金菠萝.webp',
      tags: ['现制茶饮', '甜啦啦', '百香果'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_9d_9d_61_61',
      brand: '甜啦啦',
      name: '芝芝葡葡',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__芝芝葡葡.webp',
      tags: ['现制茶饮', '甜啦啦', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_61_4_76_3',
      brand: '甜啦啦',
      name: '葡萄晶球',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__葡萄晶球.webp',
      tags: ['现制茶饮', '甜啦啦', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_66_66_5f_5f_d1_66_eb_51_5a',
      brand: '甜啦啦',
      name: '黑武士桑葚',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/甜啦啦__黑武士桑葚.webp',
      tags: ['现制茶饮', '甜啦啦', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_68_9d_18_32',
      brand: '益禾堂',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__杨枝甘露.webp',
      tags: ['现制茶饮', '益禾堂', '芒果'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_e7_d9_49',
      brand: '益禾堂',
      name: '烧仙草',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__烧仙草.webp',
      tags: ['现制茶饮', '益禾堂', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_be_ce_76_ff',
      brand: '益禾堂',
      name: '禾风奶绿',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__禾风奶绿.webp',
      tags: ['现制茶饮', '益禾堂', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_a2_46_76_36',
      brand: '益禾堂',
      name: '红豆奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__红豆奶茶.webp',
      tags: ['现制茶饮', '益禾堂', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_e0_f0_9_89',
      brand: '益禾堂',
      name: '翠峰茉莉',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__翠峰茉莉.webp',
      tags: ['现制茶饮', '益禾堂', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_9d_eb_93_93',
      brand: '益禾堂',
      name: '芝士莓莓',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__芝士莓莓.webp',
      tags: ['现制茶饮', '益禾堂', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_61_4_b0_3',
      brand: '益禾堂',
      name: '葡萄冰萃',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__葡萄冰萃.webp',
      tags: ['现制茶饮', '益禾堂', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_84_77_76_ff',
      brand: '益禾堂',
      name: '薄荷奶绿',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__薄荷奶绿.webp',
      tags: ['现制茶饮', '益禾堂', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_1c_43_4c_99',
      brand: '益禾堂',
      name: '蜜桃乌龙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__蜜桃乌龙.webp',
      tags: ['现制茶饮', '益禾堂', '乌龙'],
    ),
    DrinkRecommendation(
      id: 'drink_ca_be_2_5f_5f_7f_dc_76',
      brand: '益禾堂',
      name: '西瓜桶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/益禾堂__西瓜桶.webp',
      tags: ['现制茶饮', '益禾堂', '西瓜'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_4c_6_1b_d1',
      brand: '茶百道',
      name: '乌漆嘛黑',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__乌漆嘛黑.webp',
      tags: ['现制茶饮', '茶百道', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_65_29_65_4a_9f_9d_eb_76_36',
      brand: '茶百道',
      name: '奥利奥半熟芝士奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__奥利奥半熟芝士奶茶.webp',
      tags: ['现制茶饮', '茶百道', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_4b_63_8b_34_a2_36',
      brand: '茶百道',
      name: '手捣芋头红茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__手捣芋头红茶.webp',
      tags: ['现制茶饮', '茶百道', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_9_89_76_ff',
      brand: '茶百道',
      name: '茉莉奶绿',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__茉莉奶绿.webp',
      tags: ['现制茶饮', '茶百道', '茉莉'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_54_9d_b0_76',
      brand: '茶百道',
      name: '荔枝冰奶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__荔枝冰奶.webp',
      tags: ['现制茶饮', '茶百道', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_7f_dc_75_75',
      brand: '茶百道',
      name: '西瓜啵啵',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__西瓜啵啵.webp',
      tags: ['现制茶饮', '茶百道', '西瓜'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_46_73_89_92_9f',
      brand: '茶百道',
      name: '豆乳玉麒麟',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__豆乳玉麒麟.webp',
      tags: ['现制茶饮', '茶百道', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_c1_c2_f3_76_bb',
      brand: '茶百道',
      name: '铁观音奶冻',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__铁观音奶冻.webp',
      tags: ['现制茶饮', '茶百道', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_7e_53_5f_5f_c4_d1_30_30_4c_99',
      brand: '茶百道',
      name: '黄金椰椰乌龙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶百道__黄金椰椰乌龙.webp',
      tags: ['现制茶饮', '茶百道', '乌龙'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_ba_f4_df_6b',
      brand: '茶颜悦色',
      name: '人间烟火',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__人间烟火.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_e4_16_ff_42',
      brand: '茶颜悦色',
      name: '凤栖绿桂',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__凤栖绿桂.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_f0_f0_4c_99',
      brand: '茶颜悦色',
      name: '声声乌龙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__声声乌龙.webp',
      tags: ['现制茶饮', '茶颜悦色', '乌龙'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_b9_36_e9_d0',
      brand: '茶颜悦色',
      name: '抹茶菩提',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__抹茶菩提.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_42_b1_4',
      brand: '茶颜悦色',
      name: '桂花弄',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__桂花弄.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_df_b1_13_b7',
      brand: '茶颜悦色',
      name: '烟花易冷',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__烟花易冷.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_5d_5d_b8_22',
      brand: '茶颜悦色',
      name: '筝筝纸鸢',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__筝筝纸鸢.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_20_9c_21_70',
      brand: '茶颜悦色',
      name: '素颜锡兰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__素颜锡兰.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_a4_a4_6c_61_99',
      brand: '茶颜悦色',
      name: '纤纤马卡龙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__纤纤马卡龙.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_36_9c_a6_72_5f_5f_13_8a_11_ca',
      brand: '茶颜悦色',
      name: '蔓越阑珊',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/茶颜悦色__蔓越阑珊.webp',
      tags: ['现制茶饮', '茶颜悦色', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_16_46_e7_d9_49',
      brand: '蜜雪冰城',
      name: '外婆烧仙草',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__外婆烧仙草.webp',
      tags: ['现制茶饮', '蜜雪冰城', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_d2_53_9c_59',
      brand: '蜜雪冰城',
      name: '棒打鲜橙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__棒打鲜橙.webp',
      tags: ['现制茶饮', '蜜雪冰城', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_e1_6f_7e_99_9c',
      brand: '蜜雪冰城',
      name: '满杯百香果',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__满杯百香果.webp',
      tags: ['现制茶饮', '蜜雪冰城', '百香果'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_8b_6_61_4',
      brand: '蜜雪冰城',
      name: '芋圆葡萄',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__芋圆葡萄.webp',
      tags: ['现制茶饮', '蜜雪冰城', '葡萄'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_9d_eb_76_d6_db_63_25',
      brand: '蜜雪冰城',
      name: '芝士奶盖四季春',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__芝士奶盖四季春.webp',
      tags: ['现制茶饮', '蜜雪冰城', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_49_93_47_47_76_14',
      brand: '蜜雪冰城',
      name: '草莓摇摇奶昔',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__草莓摇摇奶昔.webp',
      tags: ['现制茶饮', '蜜雪冰城', '草莓'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_1c_43_db_63_25',
      brand: '蜜雪冰城',
      name: '蜜桃四季春',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__蜜桃四季春.webp',
      tags: ['现制茶饮', '蜜雪冰城', '蜜桃'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_ea_76_96_61',
      brand: '蜜雪冰城',
      name: '雪顶咖啡',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__雪顶咖啡.webp',
      tags: ['现制茶饮', '蜜雪冰城', '咖啡香'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_c4_43_9c_38',
      brand: '蜜雪冰城',
      name: '黄桃果霸',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__黄桃果霸.webp',
      tags: ['现制茶饮', '蜜雪冰城', '蜜桃'],
    ),
    DrinkRecommendation(
      id: 'drink_1c_ea_b0_ce_5f_5f_d1_d6_cd_e0_76_36',
      brand: '蜜雪冰城',
      name: '黑糖珍珠奶茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/蜜雪冰城__黑糖珍珠奶茶.webp',
      tags: ['现制茶饮', '蜜雪冰城', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_7_71_a2_fb_d1_1d_f_cd',
      brand: '霸王茶姬',
      name: '万山红・金丝小种',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__万山红・金丝小种.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_7_cc_28_70',
      brand: '霸王茶姬',
      name: '万里木兰',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__万里木兰.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_bb_91_57_fb_ab_70_6e_31',
      brand: '霸王茶姬',
      name: '去云南・玫瑰普洱',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__去云南・玫瑰普洱.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_fb_99_71_36',
      brand: '霸王茶姬',
      name: '寻香山茶',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__寻香山茶.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_71_ce_0_50',
      brand: '霸王茶姬',
      name: '山野栀子',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__山野栀子.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_42_a5_70_99',
      brand: '霸王茶姬',
      name: '桂馥兰香',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__桂馥兰香.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_7d_fe_a2_18_8_27_a2_8d_9',
      brand: '霸王茶姬',
      name: '白雾红尘（大红袍）',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__白雾红尘（大红袍）.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_b1_30_4c_99',
      brand: '霸王茶姬',
      name: '花田乌龙',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__花田乌龙.webp',
      tags: ['现制茶饮', '霸王茶姬', '乌龙'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_92_25_71',
      brand: '霸王茶姬',
      name: '醒春山',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__醒春山.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
    DrinkRecommendation(
      id: 'drink_38_8b_36_ec_5f_5f_52_52_ef_71',
      brand: '霸王茶姬',
      name: '青青糯山',
      category: '新茶饮',
      description: '茶香、果香和奶感都更活泼，适合给今天加一点小开心。',
      imagePath: '$_root/霸王茶姬__青青糯山.webp',
      tags: ['现制茶饮', '霸王茶姬', '快乐水替代'],
    ),
  ];

  static List<DrinkRecommendation> byCategory(String? category) {
    if (category == null || category == '全部') return drinks;
    return drinks.where((drink) => drink.category == category).toList();
  }

  static DrinkRecommendation todayRecommendation([DateTime? now]) {
    final date = now ?? DateTime.now();
    final day = DateTime(
      date.year,
      date.month,
      date.day,
    ).difference(DateTime(2026)).inDays;
    return drinks[day.abs() % drinks.length];
  }
}
