class DrinkRecommendation {
  const DrinkRecommendation({
    required this.id,
    required this.brand,
    required this.name,
    required this.category,
    required this.description,
    required this.imagePath,
    required this.tags,
  });

  final String id;
  final String brand;
  final String name;
  final String category;
  final String description;
  final String imagePath;
  final List<String> tags;
}

class DrinkCatalog {
  DrinkCatalog._();

  static const String _root = 'assets/images/drinks';

  static const categories = ['咖啡', '新茶饮', '即饮茶', '气泡', '果汁', '乳饮', '功能', '凉茶'];

  static const drinks = [
    DrinkRecommendation(
      id: 'luckin',
      brand: '瑞幸咖啡',
      name: '冰拿铁 / 生椰拿铁',
      category: '咖啡',
      description: '清爽咖啡香配一点椰乳感，适合学习前给自己轻轻提神。',
      imagePath: '$_root/瑞幸咖啡.webp',
      tags: ['冰咖啡', '椰乳', '学习搭子'],
    ),
    DrinkRecommendation(
      id: 'cotti',
      brand: '库迪咖啡',
      name: '海盐芝士 / 海盐焦糖拿铁',
      category: '咖啡',
      description: '咸甜奶盖和咖啡底很有存在感，适合想喝点厚一点的时候。',
      imagePath: '$_root/库迪咖啡.webp',
      tags: ['拿铁', '海盐', '咸甜'],
    ),
    DrinkRecommendation(
      id: 'starbucks',
      brand: '星巴克',
      name: '抹茶星冰乐 / 绿茶星冰乐',
      category: '咖啡',
      description: '抹茶冰沙感很像给下午按了暂停键，适合奖励型休息。',
      imagePath: '$_root/星巴克.webp',
      tags: ['抹茶', '冰沙', '下午茶'],
    ),
    DrinkRecommendation(
      id: 'lucky_cup',
      brand: '幸运咖',
      name: '芒果椰乳拿铁 / 厚乳拿铁',
      category: '咖啡',
      description: '果香、椰香和厚乳都很友好，适合想喝甜但不想太复杂的时候。',
      imagePath: '$_root/幸运咖.webp',
      tags: ['厚乳', '芒果', '甜口'],
    ),
    DrinkRecommendation(
      id: 'nescafe',
      brand: '雀巢咖啡',
      name: '丝滑拿铁',
      category: '咖啡',
      description: '稳定、顺口、没负担，适合需要一杯熟悉咖啡味的日子。',
      imagePath: '$_root/雀巢咖啡.webp',
      tags: ['拿铁', '即饮', '顺滑'],
    ),
    DrinkRecommendation(
      id: 'mixue',
      brand: '蜜雪冰城',
      name: '冰鲜柠檬水',
      category: '新茶饮',
      description: '酸甜清爽，适合走路、通勤和刚运动完的快乐一杯。',
      imagePath: '$_root/蜜雪冰城.webp',
      tags: ['柠檬', '清爽', '低负担'],
    ),
    DrinkRecommendation(
      id: 'guming',
      brand: '古茗',
      name: '超 A 芝士葡萄',
      category: '新茶饮',
      description: '葡萄果肉感很足，芝士奶盖让它更像一份小甜品。',
      imagePath: '$_root/古茗.webp',
      tags: ['葡萄', '芝士', '水果茶'],
    ),
    DrinkRecommendation(
      id: 'chabaidao',
      brand: '茶百道',
      name: '杨枝甘露',
      category: '新茶饮',
      description: '芒果、西柚和奶香凑在一起，适合想要热带感的一天。',
      imagePath: '$_root/茶百道.webp',
      tags: ['芒果', '西柚', '甜品感'],
    ),
    DrinkRecommendation(
      id: 'chagee',
      brand: '霸王茶姬',
      name: '伯牙绝弦',
      category: '新茶饮',
      description: '茶香更突出的一杯，适合想喝奶茶但又想保留茶味的时候。',
      imagePath: '$_root/霸王茶姬.webp',
      tags: ['原叶茶', '奶茶', '茶香'],
    ),
    DrinkRecommendation(
      id: 'aunt_shanghai',
      brand: '沪上阿姨',
      name: '血糯米奶茶',
      category: '新茶饮',
      description: '糯叽叽的饱足感很强，适合把饮料当加餐的时刻。',
      imagePath: '$_root/沪上阿姨.webp',
      tags: ['血糯米', '奶茶', '加餐'],
    ),
    DrinkRecommendation(
      id: 'heytea',
      brand: '喜茶',
      name: '多肉葡萄',
      category: '新茶饮',
      description: '葡萄果味明亮，适合想喝一杯漂亮水果茶的时候。',
      imagePath: '$_root/喜茶.webp',
      tags: ['葡萄', '水果茶', '芝士'],
    ),
    DrinkRecommendation(
      id: 'nayuki',
      brand: '奈雪的茶',
      name: '霸气芝士草莓',
      category: '新茶饮',
      description: '草莓和芝士很有仪式感，适合心情需要被照顾一下。',
      imagePath: '$_root/奈雪的茶.webp',
      tags: ['草莓', '芝士', '仪式感'],
    ),
    DrinkRecommendation(
      id: 'yihetang',
      brand: '益禾堂',
      name: '益禾烤奶',
      category: '新茶饮',
      description: '烤奶香气温柔稳定，适合想喝经典奶茶的日子。',
      imagePath: '$_root/益禾堂.webp',
      tags: ['烤奶', '经典', '奶茶'],
    ),
    DrinkRecommendation(
      id: 'shuyi',
      brand: '书亦烧仙草',
      name: '招牌烧仙草',
      category: '新茶饮',
      description: '料多、口感丰富，适合想慢慢喝完的一大杯。',
      imagePath: '$_root/书亦烧仙草.webp',
      tags: ['烧仙草', '料多', '饱足'],
    ),
    DrinkRecommendation(
      id: 'coco',
      brand: 'CoCo 都可',
      name: '百香双响炮',
      category: '新茶饮',
      description: '百香果酸甜加上双料口感，适合提起精神的小快乐。',
      imagePath: '$_root/CoCo 都可.webp',
      tags: ['百香果', '双料', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'chayan',
      brand: '茶颜悦色',
      name: '幽兰拿铁',
      category: '新茶饮',
      description: '茶、奶、奶油顶组合得很细腻，适合今天认真宠一下自己。',
      imagePath: '$_root/茶颜悦色.webp',
      tags: ['茶香', '奶油顶', '细腻'],
    ),
    DrinkRecommendation(
      id: 'linlee',
      brand: '柠季',
      name: '鸭屎香柠檬茶',
      category: '新茶饮',
      description: '柠檬和茶香都很醒神，适合犯困但不想喝咖啡的时候。',
      imagePath: '$_root/柠季.webp',
      tags: ['柠檬茶', '鸭屎香', '醒神'],
    ),
    DrinkRecommendation(
      id: 'sweet7',
      brand: '甜啦啦',
      name: '冰鲜柠檬水',
      category: '新茶饮',
      description: '简单清凉的一杯，适合天气热、嘴巴想要酸甜感的时候。',
      imagePath: '$_root/甜啦啦.webp',
      tags: ['柠檬', '冰饮', '清凉'],
    ),
    DrinkRecommendation(
      id: 'yidiandian',
      brand: '一点点',
      name: '波霸奶茶',
      category: '新茶饮',
      description: '珍珠奶茶的经典答案，适合想回到熟悉口味的一天。',
      imagePath: '$_root/一点点.webp',
      tags: ['波霸', '奶茶', '经典'],
    ),
    DrinkRecommendation(
      id: 'ksf_ice_tea',
      brand: '康师傅',
      name: '冰红茶',
      category: '即饮茶',
      description: '很有夏天记忆点的一瓶，适合想喝爽快茶味甜饮的时候。',
      imagePath: '$_root/冰红茶.webp',
      tags: ['红茶', '瓶装', '冰爽'],
    ),
    DrinkRecommendation(
      id: 'ksf_green',
      brand: '康师傅',
      name: '绿茶',
      category: '即饮茶',
      description: '清甜绿茶味，适合吃饭或走路时顺手带一瓶。',
      imagePath: '$_root/绿茶.webp',
      tags: ['绿茶', '瓶装', '清甜'],
    ),
    DrinkRecommendation(
      id: 'ksf_jasmine',
      brand: '康师傅',
      name: '茉莉清茶',
      category: '即饮茶',
      description: '茉莉香气更轻柔，适合想喝茶味但不想太浓的时候。',
      imagePath: '$_root/茉莉清茶.webp',
      tags: ['茉莉', '清茶', '轻盈'],
    ),
    DrinkRecommendation(
      id: 'uni_ice_tea',
      brand: '统一',
      name: '统一冰红茶',
      category: '即饮茶',
      description: '酸甜茶感直接，适合想快速获得一口冰爽。',
      imagePath: '$_root/统一冰红茶.webp',
      tags: ['红茶', '瓶装', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'assam',
      brand: '统一',
      name: '阿萨姆奶茶',
      category: '即饮茶',
      description: '奶茶感浓郁稳定，适合想要方便又有满足感的一瓶。',
      imagePath: '$_root/阿萨姆奶茶.webp',
      tags: ['奶茶饮料', '阿萨姆', '浓郁'],
    ),
    DrinkRecommendation(
      id: 'plum_green',
      brand: '统一',
      name: '青梅绿茶',
      category: '即饮茶',
      description: '青梅酸甜混着绿茶，适合需要一点清爽转场的时候。',
      imagePath: '$_root/青梅绿茶.webp',
      tags: ['青梅', '绿茶', '酸甜'],
    ),
    DrinkRecommendation(
      id: 'oriental_leaf',
      brand: '农夫山泉',
      name: '东方树叶',
      category: '即饮茶',
      description: '无糖茶的稳妥选择，适合想清口、控糖或配餐。',
      imagePath: '$_root/东方树叶.webp',
      tags: ['无糖茶', '配餐', '清口'],
    ),
    DrinkRecommendation(
      id: 'tea_pi',
      brand: '农夫山泉',
      name: '茶 π',
      category: '即饮茶',
      description: '果味茶更活泼，适合想在瓶装茶里喝到一点花样。',
      imagePath: '$_root/茶 π.webp',
      tags: ['果味茶', '瓶装', '轻甜'],
    ),
    DrinkRecommendation(
      id: 'suntory_oolong',
      brand: '三得利',
      name: '无糖乌龙茶',
      category: '即饮茶',
      description: '乌龙茶感干净利落，适合饭后和长时间工作时喝。',
      imagePath: '$_root/无糖乌龙茶.webp',
      tags: ['乌龙', '无糖', '饭后'],
    ),
    DrinkRecommendation(
      id: 'genki_ice_tea',
      brand: '元气森林',
      name: '冰茶系列',
      category: '即饮茶',
      description: '冰茶口味更轻快，适合想喝甜茶但别太厚重的时候。',
      imagePath: '$_root/冰茶系列.webp',
      tags: ['冰茶', '轻甜', '瓶装'],
    ),
    DrinkRecommendation(
      id: 'vita_lemon',
      brand: '维他',
      name: '维他柠檬茶',
      category: '即饮茶',
      description: '柠檬茶味很醒目，适合困顿下午来一点酸甜冲击。',
      imagePath: '$_root/维他柠檬茶.webp',
      tags: ['柠檬茶', '酸甜', '醒神'],
    ),
    DrinkRecommendation(
      id: 'coca',
      brand: '可口可乐',
      name: '可口可乐',
      category: '气泡',
      description: '快乐水就是快乐水，适合想给今天加一点气泡声。',
      imagePath: '$_root/可口可乐.webp',
      tags: ['碳酸', '经典', '快乐水'],
    ),
    DrinkRecommendation(
      id: 'pepsi',
      brand: '百事可乐',
      name: '百事可乐',
      category: '气泡',
      description: '直接、冰爽、很放松，适合搭配休息和小零食。',
      imagePath: '$_root/百事可乐.webp',
      tags: ['碳酸', '冰爽', '零食搭子'],
    ),
    DrinkRecommendation(
      id: 'genki_peach',
      brand: '元气森林',
      name: '白桃气泡水',
      category: '气泡',
      description: '白桃香和气泡感都很轻，适合想喝甜感但不想太腻。',
      imagePath: '$_root/白桃气泡水.webp',
      tags: ['白桃', '气泡水', '轻盈'],
    ),
    DrinkRecommendation(
      id: 'genki_sparkling',
      brand: '元气森林',
      name: '多种果味气泡水',
      category: '气泡',
      description: '果味气泡给选择困难一个简单答案，适合今天想要新鲜感。',
      imagePath: '$_root/多种果味气泡水.webp',
      tags: ['果味', '气泡水', '新鲜感'],
    ),
    DrinkRecommendation(
      id: 'c100',
      brand: '农夫山泉',
      name: '水溶 C100',
      category: '果汁',
      description: '酸酸甜甜的维 C 感，适合想喝清亮果味的时候。',
      imagePath: '$_root/水溶 C100.webp',
      tags: ['维C', '果味', '清爽'],
    ),
    DrinkRecommendation(
      id: 'nfc',
      brand: '农夫山泉',
      name: 'NFC 果汁',
      category: '果汁',
      description: '更像认真喝一杯果汁，适合早餐或加餐时刻。',
      imagePath: '$_root/NFC.webp',
      tags: ['NFC', '果汁', '早餐'],
    ),
    DrinkRecommendation(
      id: 'minute_maid',
      brand: '美汁源',
      name: '果粒橙',
      category: '果汁',
      description: '果粒口感很有记忆点，适合想喝橙味甜饮的时候。',
      imagePath: '$_root/美汁源.webp',
      tags: ['橙汁', '果粒', '经典'],
    ),
    DrinkRecommendation(
      id: 'suntory_lemon',
      brand: '三得利',
      name: '沁柠水',
      category: '果汁',
      description: '柠檬风味更轻，适合想要清爽但不想太甜的时候。',
      imagePath: '$_root/沁柠水.webp',
      tags: ['柠檬', '清淡', '轻甜'],
    ),
    DrinkRecommendation(
      id: 'hope_water',
      brand: '好望水',
      name: '望山楂 / 山楂草本饮',
      category: '果汁',
      description: '山楂和草本风味很东方，适合饭后或想换个口味。',
      imagePath: '$_root/好望水.webp',
      tags: ['山楂', '草本', '饭后'],
    ),
    DrinkRecommendation(
      id: 'ad_calcium',
      brand: '娃哈哈',
      name: 'AD 钙奶',
      category: '乳饮',
      description: '童年味道很明显，适合今天想喝一点轻松和可爱。',
      imagePath: '$_root/AD钙.webp',
      tags: ['乳饮', '童年', '甜口'],
    ),
    DrinkRecommendation(
      id: 'vita_soy',
      brand: '维他',
      name: '维他豆奶',
      category: '乳饮',
      description: '豆香温柔，适合早餐、夜晚或不想喝茶咖的时候。',
      imagePath: '$_root/维他豆奶.webp',
      tags: ['豆奶', '植物蛋白', '温柔'],
    ),
    DrinkRecommendation(
      id: 'yakult',
      brand: '养乐多',
      name: '养乐多乳酸菌饮品',
      category: '乳饮',
      description: '小小一瓶酸甜明亮，适合饭后给自己一个轻快收尾。',
      imagePath: '$_root/养乐多.webp',
      tags: ['乳酸菌', '酸甜', '饭后'],
    ),
    DrinkRecommendation(
      id: 'scream',
      brand: '尖叫',
      name: '尖叫运动饮料',
      category: '功能',
      description: '运动感很强，适合健身、出汗或长时间外出之后。',
      imagePath: '$_root/尖叫.webp',
      tags: ['运动', '补水', '出汗后'],
    ),
    DrinkRecommendation(
      id: 'eastroc',
      brand: '东鹏特饮',
      name: '东鹏特饮',
      category: '功能',
      description: '能量饮料存在感强，适合确实需要打起精神的场景。',
      imagePath: '$_root/东鹏特饮.webp',
      tags: ['能量', '提神', '慎喝'],
    ),
    DrinkRecommendation(
      id: 'mizone',
      brand: '脉动',
      name: '脉动维生素饮料',
      category: '功能',
      description: '运动后或户外时很顺手，适合补一点清爽果味。',
      imagePath: '$_root/脉动.webp',
      tags: ['维生素', '运动', '清爽'],
    ),
    DrinkRecommendation(
      id: 'wanglaoji',
      brand: '王老吉',
      name: '王老吉凉茶',
      category: '凉茶',
      description: '凉茶的经典答案，适合火锅、烧烤或重口味之后。',
      imagePath: '$_root/王老吉凉茶.webp',
      tags: ['凉茶', '草本', '配餐'],
    ),
  ];

  static List<DrinkRecommendation> byCategory(String? category) {
    if (category == null || category == '全部') return drinks;
    return drinks.where((drink) => drink.category == category).toList();
  }

  static DrinkRecommendation todayRecommendation([DateTime? now]) {
    final date = now ?? DateTime.now();
    final day = DateTime(
      date.year,
      date.month,
      date.day,
    ).difference(DateTime(2026)).inDays;
    return drinks[day.abs() % drinks.length];
  }
}
